name: Laravel testing
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code  
        uses: actions/checkout@v4

      - name: Run test command
      # for example install composer
        run: php artisan test --parallel